heat_template_version: 2015-04-30

description: Compute node hieradata for NUMA configuration

parameters:
  server:
    description: ID of the compute node to apply this config to
    type: string
  LibvirtCPUPinSet:
    description: A list or range of physical CPU cores to reserve for virtual machine processes
    type: string
  DpdkPmdDriver:
    description: Driver to use to bind dpdk NIC
    type: string
    default: "uio_pci_generic"

resources:
  ComputeNumaConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        hiera:
          datafiles:
            numa:
              mapped_data:
                nova::compute::vcpu_pin_set: {get_input: vcpu_pin_set}
                dpdk_pmd_type: {get_input: dpdk_pmd_type}
  ComputeNumaDeployment:
    type: OS::Heat::StructuredDeployment
    properties:
      config: {get_resource: ComputeNumaConfig}
      server: {get_param: server}
      input_values:
        vcpu_pin_set: {get_param: LibvirtCPUPinSet}
        dpdk_pmd_type: {get_param: DpdkPmdDriver}

  ComputeNumaPuppetConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: puppet
      config:
        get_file: manifests/ovs_dpdk.pp

  ComputeNumaPuppetDeployment:
    depends_on: ComputeNumaDeployment
    type: OS::Heat::StructuredDeployment
    properties:
      server: {get_param: server}
      config: {get_resource: ComputeNumaPuppetConfig}

outputs:
  deploy_stdout:
    description: Output of the extra hiera data deployment
    value: {get_attr: [ComputeNumaDeployment, deploy_stdout]}
